from __future__ import annotations

from enum import Enum

class CandidateStage(str, Enum):
    DISCOVERED = "DISCOVERED"
    DEDUPED = "DEDUPED"
    RANKED_FOR_SCRAPE = "RANKED_FOR_SCRAPE"
    SCRAPED = "SCRAPED"
    EVIDENCE_EXTRACTED = "EVIDENCE_EXTRACTED"
    SCORED = "SCORED"
    REJECTED_NON_PRODUCT_PAGE = "REJECTED_NON_PRODUCT_PAGE"
    REJECTED_UNSCRAPABLE = "REJECTED_UNSCRAPABLE"
    REJECTED_VARIANT_MISMATCH = "REJECTED_VARIANT_MISMATCH"
    REJECTED_WEAK_EVIDENCE = "REJECTED_WEAK_EVIDENCE"
    REJECTED_WRONG_PRODUCT = "REJECTED_WRONG_PRODUCT"
    PROMOTED_FOR_LLM = "PROMOTED_FOR_LLM"
    LLM_VERIFIED_EXACT = "LLM_VERIFIED_EXACT"
    SELECTED_FINAL = "SELECTED_FINAL"
