[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = true
enableXsrfProtection = true
fileWatcherType = "poll"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#4EA1FF"
